### ISSUE TITLE
EMFILE error - too many files open

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database-obj-importer#1]
Tried to run the uploader with the Mitte conversion, got an error at:

```
/building-database-obj-importer/index.js:419
        output.latitude = coords[1],
                                ^
TypeError: Cannot read property '1' of undefined
```

In seems getOrigin() is failing because it tries to set 'coords' before the LineReader has read anything (https://github.com/polygon-city/building-database-obj-importer/blob/master/index.js#L393) – this is because LineReader is erroring out with EMFILE – so it looks like we need a batching step of some kind to handle directories with more files than the MAX_OPEN value – on OS X this is apparently only 256: http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me

**Comment by robhawkes** [comment]
I've pushed 27f7845 with a little queuing mechanism for the file processing. This is currently limited to 100 files at a time so should be well within the EMFILE limits.

I'm unable to test this properly without spamming the test server (and being unable to delete them) so let me know how you get on.

**Comment by meetar** [comment]
Getting some errors…

if I change https://github.com/polygon-city/building-database-obj-importer/blob/master/index.js#L264 to:

```
try {
  var savedBuilding = JSON.parse(body);
} catch (e) {
  console.log('error parsing JSON:\n', body);
  throw e;
}
```

I get:

```
error parsing JSON:
 <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

/building-database-obj-importer/index.js:268
      throw e;
            ^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/building-database-obj-importer/index.js:265:32)
    at Request.self.callback (/building-database-obj-importer/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/building-database-obj-importer/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/building-database-obj-importer/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Assume this is related to the recent server config changes…

**Comment by robhawkes** [comment]
Does this happen for all buildings? I've not seen it before so it could be related to a recent change.

**Comment by meetar** [comment]
I can't tell for sure – it looks like some files are processed without
complaint, but that might just be the asynchronous nature of the app.
Nothing is ever uploaded, so I suspect it is in fact all buildings.

**Comment by robhawkes** [comment]
Hmm, I can't replicate it locally so it's gotta be something to do with the server setup – either the auth or the recent changes.

I don't have an admin account on the server so I can't test – I've created a normal account under my personal email so if you can flip the admin switch in the DB for me then I can check if I get the same error from my side when uploading to the dev site (I'd guess yes with it being a 502 error).

If it helps, we can actually revert the changes Baldur made for CORS and auth as we don't need it right now as the demo is hosted on the same server. Might be useful for testing.

**Comment by meetar** [comment]
Some of them work, and then I get the same `Cannot read property '1' of undefined` error as before, but for a slightly different reason – if at https://github.com/polygon-city/building-database-obj-importer/blob/master/index.js#L446 I insert this line:

```
console.warn('getorigin error:', err);
```

I see: 

getorigin error: { [Error: ENFILE, open 'output/BLDG_0003000a0018eb3d.obj']
      errno: -23,
      code: 'ENFILE',
      path: 'output/BLDG_0003000a0018eb3d.obj' }

So I tried dropping the queue limit from 100, and if I re-use a batch number it seems to work better, but it only ever processes about as many total buildings as the queue limit – and if I don't re-use the batch number, I get the ENFILE error no matter how low the queue limit is.

**Comment by robhawkes** [comment]
_Edit: I can now replicate this so hoping for a fix soon!_

I'm looking at this now – can't replicate it yet (able to pump through thousands of buildings without trouble) but trying a few other approaches to see what I can do.

The original queue should stop EMFILE / ENFILE errors so not yet sure why they're still being triggered.

**Comment by robhawkes** [comment]
2625364 should fix this – I wasn't closing the `LineReader` instances properly so they were keeping the file open behind the scenes. I've also reduced the queue length and moved a couple of other bits around, though these weren't the cause of the issue.

Let me know how you get on with this version.

**Comment by meetar** [comment]
Original problem is solved!

**Comment by meetar** [comment]
For the record, while testing https://github.com/polygon-city/building-database-obj-importer/issues/2 I've determined that queue size appears to have no effect on upload speed or incidence of 504 errors.
