### ISSUE TITLE
restarted uploads exit when queue is empty

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database-obj-importer#3]
To reproduce with a fresh config.js file:
1. start an upload and note the batch ID
2. cancel the upload
3. add the batch ID to the config.js "batchID" parameter
4. restart the upload

Result:
The upload will finish the buildings which were in the queue at the time of the cancellation, then exit the process with no errors.

If all the buildings had uploaded sucessfully, the console output will be n lines of "Skipping building as already uploaded" where n is the length of the queue.

Expected result:
The upload will continue as before, refreshing the queue with new buildings from the target upload directory.

**Comment by robhawkes** [comment]
I'm a bit confused as to what's meant to be going wrong here.

The way the batch uploader currently works, if you cancel a batch mid-upload and restart it, then it'll upload any file in the directory that wasn't successfully uploaded last time. No queue is saved, it just checks the files on the server against the files in the directory you're trying to upload. 

Any files that have already been uploaded under this batch ID will output a "Skipping building…" message, which is just for debugging purposes.

Once all the files in the directory have been uploaded, re-running the upload with the same batch ID would output "Skipping building…" for every single file.

Is this not happening?

Do you mean that this process is currently manual (ie. you have to re-run the upload), whereas you'd rather it automated (ie. it'll keep retrying failed uploads until all buildings are added)?

**Comment by meetar** [comment]
I'll try to clarify the behavior I was seeing yesterday:

Setup:
- set queue length to 10 and start an upload
- cancel the upload after 4 files have been uploaded
- restart the upload with the same batch ID

Result:
the process will log "skipping building" 4 times, upload 6 buildings, and exit. If I restart it again, I see 10 "skipping buildings" logs, and the process will exit.

If I cancel in the middle of a longer job, I the process will still log some number of "skipping building" lines, upload n buildings where n < length of the queue, then exit. If I restart the job numerous times, I'll see more "skipping buildings" and fewer "building added" messages each time until it ceases to upload buildings, but it won't progress in the directory past the point where it was the first time the job was cancelled.

Doesn't make any sense to me either – I have no idea how any state is being maintained between successive executions of the script, or what mechanism is causing the script to exit. I'll attempt to verify this behavior today and report back.

**Comment by meetar** [comment]
For a while it looked as though when a batch was resumed, the batch length was being set to the length of the current queue – I added `cb(exclude);` at https://github.com/polygon-city/building-database-obj-importer/blob/master/index.js#L433 and that seems to have fixed it, but now I'm seeing another error… I'll close this for now.

**Comment by robhawkes** [comment]
It does look like I forgot a callback there so good spot, I've added that in so it should now release control so more buildings can be added to the queue. I think that's the fix here so we can tackle the new problem in another issue.
